version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: future-isa-postgres
    restart: always
    environment:
      POSTGRES_USER: future_isa
      POSTGRES_PASSWORD: future_isa_password
      POSTGRES_DB: future_isa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
